steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/inford-439722/image-registry/yahweh-game-backend",
        "-f",
        "dockerfile",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/inford-439722/image-registry/yahweh-game-backend",
      ]
options:
  logging: CLOUD_LOGGING_ONLY